### ISSUE TITLE
PerWorldInventory integration

### ISSUE THREAD

**Issue by malpkakefirek** [Jannyboy11/InvSee-plus-plus#12] opened 2021-10-04 10:00 UTC
Everyone's inventory seem to be empty when using `PWI{...` as an argument when using command `/isee` (no matter the values i put for the properties)

Note: I have `load-data-on-join: true` in PWI's config

this is my `config.yml` in PWI: https://pastebin.com/ZhLLQxZm
this is my `worlds.yml` in PWI: https://pastebin.com/E5MLYgBf
PWI version: `2.3.2`
InvSee++ version: `0.10.2`
Minecraft version: `Paper version git-Paper-257 (MC: 1.17.1)`
Java version: `16`

**Comment by Jannyboy11** [comment] 2021-11-23 16:52
Apologies for the late reply. I don't have time to investigate this any time soon. I'll hopefully have this fixed when Spigot 1.18 releases.

**Comment by Jannyboy11** [comment] 2022-08-18 14:15
Can't reproduce, I need more details. But PerWorldInventory is an abandoned plugin anyway. You're better off trying out Multiverse-Inventories or MyWorlds.

**Comment by Jannyboy11** [comment] 2022-08-18 14:24
Alright then, I will close this issue for now. Feel free to comment and I'll re-open.

**Closed by Jannyboy11** 2022-08-18 14:24 UTC
