### ISSUE TITLE
Error console about "_global.log"

### ISSUE THREAD

**Issue by KingCueio** [Jannyboy11/InvSee-plus-plus#51] opened 2023-05-02 13:00 UTC
[12:55:10 ERROR]: [InvSee++] Could not create new file handler
java.io.IOException: Couldn't get lock for /home/container/plugins/InvSeePlusPlus/InvSee++ logs/_global.log
        at java.util.logging.FileHandler.openFiles(FileHandler.java:491) ~[?:?]
        at java.util.logging.FileHandler.<init>(FileHandler.java:342) ~[?:?]
        at com.janboerman.invsee.spigot.api.logging.LogOutputImpl.<init>(LogOutput.java:90) ~[InvSee++.jar:?]
        at com.janboerman.invsee.spigot.api.logging.LogOutputImpl.of(LogOutput.java:127) ~[InvSee++.jar:?]
        at com.janboerman.invsee.spigot.api.logging.LogOutput.make(LogOutput.java:32) ~[InvSee++.jar:?]
        at com.janboerman.invsee.spigot.impl_1_17_1_R1.MainNmsContainer.<init>(MainNmsContainer.java:111) ~[InvSee++.jar:?]
        at com.janboerman.invsee.spigot.impl_1_17_1_R1.InvseeImpl.openMainSpectatorInventory(InvseeImpl.java:89) ~[InvSee++.jar:?]
        at com.janboerman.invsee.spigot.api.InvseeAPI.lambda$spectateInventory$28(InvseeAPI.java:832) ~[InvSee++.jar:?]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887) ~[?:?]
        at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2325) ~[?:?]
        at com.janboerman.invsee.spigot.api.InvseeAPI.spectateInventory(InvseeAPI.java:828) ~[InvSee++.jar:?]
        at com.janboerman.invsee.spigot.api.InvseeAPI.spectateInventory(InvseeAPI.java:388) ~[InvSee++.jar:?]
        at com.janboerman.invsee.spigot.InvseeCommandExecutor.onCommand(InvseeCommandExecutor.java:155) ~[InvSee++.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2262) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2073) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2054) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1475) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-411]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Jannyboy11** [comment] 2023-05-03 06:55
Thank you for the report. The plugin couldn't create the log file _global.log. This could be a mistake on my part, but it could also be a unix file permissions issue. Does this error prevent you from spectating the target's inventory?

**Comment by Jannyboy11** [comment] 2023-05-09 15:48
I think I found the cause of the issue; the log Handlers need to be closed when the plugin shuts down.

**Comment by Jannyboy11** [comment] 2023-05-18 10:23
Fixed as of https://github.com/Jannyboy11/InvSee-plus-plus/commit/6ae9c596940fe847e04c8ca32a639eb2587efaa6

**Closed by Jannyboy11** 2023-05-18 10:23 UTC
Labels: bug
