### ISSUE TITLE
Invsee ++ Instant crash at server start

### ISSUE THREAD

**Issue by redico** [Jannyboy11/InvSee-plus-plus#86] opened 2023-10-14 23:28 UTC
I just installed invsee++ on my server but it only deactivates itself even with plugman. I looked for a solution but nothing. I have below some error report which blocks the activation of the plugin. I would like to point out that my server is 1.20 and that I have the following plugins on it : - CoreProtect ; - EliteMobs ; - Essantial ; - Graves ; - Gsit ; - Invsee ++ ( with also give and clear ) ; - LibsDisguises ; - LuckPerm ; - Model Engine ; - Multiverse Core ; - Placeholder Api ; - Plasmo Voice ; - Plugman X ; - ProtolLib ; - SkinsRestorer ; - TAB ; - Terraform Generator ; - UltimateAutoRestart ; - UltimateModération ; - ViaVersion ; - WorldEdit ; - WorldGuard ; - Essantials Chat

Here are the reports :
1st :
![image](https://github.com/Jannyboy11/InvSee-plus-plus/assets/60150479/2d56447e-77e8-40df-9307-745430caf829)

2nd :
[01:28:21 WARN]: Enabled plugin with unregistered ConfiguredPluginClassLoader InvSeePlusPlus v0.24.1
[01:28:21 ERROR]: Error occurred while enabling InvSeePlusPlus v0.24.1 (Is it up to date?)
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:840) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:339) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:517) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:472) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:195) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at com.janboerman.invsee.spigot.InvseePlusPlus.makeScheduler(InvseePlusPlus.java:424) ~[InvSee++.jar:?]
        at com.janboerman.invsee.spigot.InvseePlusPlus.onEnable(InvseePlusPlus.java:76) ~[InvSee++.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.jar:git-Paper-17]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.jar:git-Paper-17]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
        at com.rylinaux.plugman.util.BukkitPluginUtil.enable(BukkitPluginUtil.java:135) ~[PlugManX.jar:?]
        at com.rylinaux.plugman.util.PaperPluginUtil.enable(PaperPluginUtil.java:157) ~[PlugManX.jar:?]
        at com.rylinaux.plugman.command.EnableCommand.execute(EnableCommand.java:130) ~[PlugManX.jar:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:97) ~[PlugManX.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:929) ~[paper-1.20.jar:git-Paper-17]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.jar:git-Paper-17]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[paper-1.20.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:308) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2298) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2258) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.jar:git-Paper-17]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.jar:git-Paper-17]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.jar:git-Paper-17]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.jar:git-Paper-17]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.jar:git-Paper-17]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.jar:git-Paper-17]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.jar:git-Paper-17]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.jar:git-Paper-17]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[01:28:21 INFO]: [InvSee++] Disabling InvSeePlusPlus v0.24.1

I also test with the last version of the plugin

**Comment by Jannyboy11** [comment] 2023-10-19 10:11
To me this looks like a bug in Paper, it is trying to enable the InvSee++_Clear plugin before it enables the InvSee++ main plugin. I will investigate when I have time.

**Comment by Jannyboy11** [comment] 2023-10-29 19:42
Closing this as invalid because OP is no longer responding, and it is likely caused by an incompatible version of Paper.

**Closed by Jannyboy11** 2023-10-29 19:42 UTC
Labels: invalid
