### ISSUE TITLE
plugin won`t start

### ISSUE THREAD

**Issue by highestinthespb** [Jannyboy11/InvSee-plus-plus#85] opened 2023-09-26 15:26 UTC
core: Mohist-1.20.1-449

[18:20:40 INFO]: [InvSee++] Enabling InvSeePlusPlus v0.24.1
[18:20:41 ERROR]: Error occurred while enabling InvSeePlusPlus v0.24.1 (Is it up to date?)
java.lang.ClassFormatError: Duplicate method name "m_150399_" with signature "(IILnet.minecraft.world.inventory.ClickType;Lnet.minecraft.world.entity.player.Player;)V" in class file com/janboerman/invsee/spigot/impl_1_20_1_R1/MainNmsContainer
at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
at java.lang.ClassLoader.defineClass(ClassLoader.java:1013) ~[?:?]
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:240) ~[forge-1.20.1-47.1.76-universal.jar%23178!/:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:143) ~[forge-1.20.1-47.1.76-universal.jar%23178!/:?]
at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:138) ~[forge-1.20.1-47.1.76-universal.jar%23178!/:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
at com.janboerman.invsee.spigot.Impl_1_20_1.<init>(Setup.java:117) ~[?:?]
at com.janboerman.invsee.spigot.Setup.setup(Setup.java:50) ~[?:?]
at com.janboerman.invsee.spigot.InvseePlusPlus.onEnable(InvseePlusPlus.java:79) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:347) ~[forge-1.20.1-47.1.76-universal.jar%23178!/:?]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) ~[forge-1.20.1-47.1.76-universal.jar%23178!/:?]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:482) ~[forge-1.20.1-47.1.76-universal.jar%23178!/:?]
at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:548) ~[forge-1.20.1-47.1.76-universal.jar%23178!/:997de31d-ddc9a2dad-d2eba2c8-47.2.0]
at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:461) ~[forge-1.20.1-47.1.76-universal.jar%23178!/:997de31d-ddc9a2dad-d2eba2c8-47.2.0]
at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:437) ~[server-1.20.1-20230612.114412-srg.jar%23173!/:?]
at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:339) ~[server-1.20.1-20230612.114412-srg.jar%23173!/:?]
at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:219) ~[server-1.20.1-20230612.114412-srg.jar%23173!/:?]
at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:851) ~[server-1.20.1-20230612.114412-srg.jar%23173!/:?]
at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:279) ~[server-1.20.1-20230612.114412-srg.jar%23173!/:?]
at java.lang.Thread.run(Thread.java:1623) [?:?]
[18:20:41 INFO]: [InvSee++] Disabling InvSeePlusPlus v0.24.1

**Comment by Jannyboy11** [comment] 2023-09-26 17:28
This is a bug in the pkugin class bytecode transformer in Mohist. Closing this as a duplicate of https://github.com/Jannyboy11/InvSee-plus-plus/issues/83

**Closed by Jannyboy11** 2023-09-26 17:28 UTC
Labels: duplicate

**Comment by Jannyboy11** [comment] 2024-01-01 15:45
You can use this release if you want to stay on 1.20.1: https://github.com/Jannyboy11/InvSee-plus-plus/releases/tag/v0.24.8-Mohist-Arclight-1.20.1
