### ISSUE TITLE
I found a error:

### ISSUE THREAD

**Issue by thiagogebrimm** [Jannyboy11/InvSee-plus-plus#14] opened 2021-11-22 16:46 UTC
```
[13:45:30 ERROR]: Could not pass event PlayerJoinEvent to InvSeePlusPlus v0.10.2-SNAPSHOT
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.Inventory.getType()" because "inventory" is null
        at org.bukkit.craftbukkit.v1_17_R1.inventory.CraftContainer.getNotchInventoryType(CraftContainer.java:92) ~[patched_1.17.1.jar:git-Purpur-1427]
        at org.bukkit.craftbukkit.v1_17_R1.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:323) ~[patched_1.17.1.jar:git-Purpur-1427]
        at com.janboerman.invsee.spigot.api.InvseeAPI$PlayerListener.onJoin(InvseeAPI.java:504) ~[InvSee++.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[patched_1.17.1.jar:git-Purpur-1427]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1427]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1427]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Purpur-1427]
        at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:360) ~[patched_1.17.1.jar:git-Purpur-1427]
        at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:302) ~[patched_1.17.1.jar:git-Purpur-1427]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:322) ~[app:?]
        at net.minecraft.network.Connection.tick(Connection.java:555) ~[app:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:201) ~[app:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1679) ~[patched_1.17.1.jar:git-Purpur-1427]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:528) ~[patched_1.17.1.jar:git-Purpur-1427]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1505) ~[patched_1.17.1.jar:git-Purpur-1427]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1298) ~[patched_1.17.1.jar:git-Purpur-1427]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1427]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
[13:45:30 INFO]: OrangeFox_[/177.89.91.249:36852] logged in with entity id 16898 at ([world]4.242659826646514, 62.0, 2.0650432946823067)
```

**Comment by Jannyboy11** [comment] 2021-11-23 16:50
Right. I found the cause for this. Thank you for reporting! Will be fixed in the next release!

**Closed** 2021-11-24 16:06 UTC
